# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='calculator.proto',
  package='com.codenotfound.grpc.helloworld',
  syntax='proto3',
  serialized_options=_b('P\001'),
  serialized_pb=_b('\n\x10\x63\x61lculator.proto\x12 com.codenotfound.grpc.helloworld\"#\n\x11\x43\x61lculatorRequest\x12\x0e\n\x06result\x18\x01 \x01(\x02\"$\n\x11\x43\x61lculatorReponse\x12\x0f\n\x07result2\x18\x01 \x01(\x02\"\x17\n\x06Number\x12\r\n\x05value\x18\x01 \x01(\x02\x32p\n\nCalculator\x12\x62\n\nSquareRoot\x12(.com.codenotfound.grpc.helloworld.Number\x1a(.com.codenotfound.grpc.helloworld.Number\"\x00\x42\x02P\x01\x62\x06proto3')
)




_CALCULATORREQUEST = _descriptor.Descriptor(
  name='CalculatorRequest',
  full_name='com.codenotfound.grpc.helloworld.CalculatorRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='com.codenotfound.grpc.helloworld.CalculatorRequest.result', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=89,
)


_CALCULATORREPONSE = _descriptor.Descriptor(
  name='CalculatorReponse',
  full_name='com.codenotfound.grpc.helloworld.CalculatorReponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result2', full_name='com.codenotfound.grpc.helloworld.CalculatorReponse.result2', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=127,
)


_NUMBER = _descriptor.Descriptor(
  name='Number',
  full_name='com.codenotfound.grpc.helloworld.Number',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='com.codenotfound.grpc.helloworld.Number.value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=152,
)

DESCRIPTOR.message_types_by_name['CalculatorRequest'] = _CALCULATORREQUEST
DESCRIPTOR.message_types_by_name['CalculatorReponse'] = _CALCULATORREPONSE
DESCRIPTOR.message_types_by_name['Number'] = _NUMBER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CalculatorRequest = _reflection.GeneratedProtocolMessageType('CalculatorRequest', (_message.Message,), dict(
  DESCRIPTOR = _CALCULATORREQUEST,
  __module__ = 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:com.codenotfound.grpc.helloworld.CalculatorRequest)
  ))
_sym_db.RegisterMessage(CalculatorRequest)

CalculatorReponse = _reflection.GeneratedProtocolMessageType('CalculatorReponse', (_message.Message,), dict(
  DESCRIPTOR = _CALCULATORREPONSE,
  __module__ = 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:com.codenotfound.grpc.helloworld.CalculatorReponse)
  ))
_sym_db.RegisterMessage(CalculatorReponse)

Number = _reflection.GeneratedProtocolMessageType('Number', (_message.Message,), dict(
  DESCRIPTOR = _NUMBER,
  __module__ = 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:com.codenotfound.grpc.helloworld.Number)
  ))
_sym_db.RegisterMessage(Number)


DESCRIPTOR._options = None

_CALCULATOR = _descriptor.ServiceDescriptor(
  name='Calculator',
  full_name='com.codenotfound.grpc.helloworld.Calculator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=154,
  serialized_end=266,
  methods=[
  _descriptor.MethodDescriptor(
    name='SquareRoot',
    full_name='com.codenotfound.grpc.helloworld.Calculator.SquareRoot',
    index=0,
    containing_service=None,
    input_type=_NUMBER,
    output_type=_NUMBER,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALCULATOR)

DESCRIPTOR.services_by_name['Calculator'] = _CALCULATOR

# @@protoc_insertion_point(module_scope)
